name: app test

on: push

env:
  node-version: 18
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.changes.outputs.app }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yml

  test:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.app == 'true' }}
    env:
      RESAS_API_URL: ${{ secrets.RESAS_API_URL }}
      RESAS_API_KEY: ${{ secrets.RESAS_API_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          run_install: false
          version: 7.26.3

      - name: get pnpm store
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: install
        run: pnpm install --frozen-lockfile

      - name: unit test
        run: pnpm turbo test

  app-test-check:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "test is successfully executed."
